import './globals.css'
import { Noto_Sans_Arabic } from 'next/font/google'

const noto_sans = Noto_Sans_Arabic({
  subsets: ['arabic'],
  variable: '--font-noto-sans'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ar" suppressHydrationWarning>
      <head>
        <script src="https://kit.fontawesome.com/3fe7c2032c.js" crossorigin="anonymous"></script>
      </head>
      <body className={`${noto_sans.variable} font-sans `} dir='rtl' >
        {children}
      </body>
    </html>
  )
}
