import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

import './globals.css'
import { Noto_Sans_Arabic } from 'next/font/google'

const noto_sans = Noto_Sans_Arabic({
  subsets: ['arabic'],
  variable: '--font-noto-sans'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ar" suppressHydrationWarning>
      <body className={`${noto_sans.variable} font-sans `} dir='rtl' >
        {children}
      </body>
    </html>
  )
}
